############################# Metricbeat ######################################
metricbeat.modules:
- module: elasticsearch
  enabled: true
  metricsets:
    - node
    - node_stats
    - pending_tasks
    - shard
    - index
    - index_recovery
    - index_summary
  period: 10s
  hosts: ["http://es01:9200"]
  username: "elastic"
  password: "changeme"
  xpack.enabled: true

- module: logstash
  enabled: true
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["http://ls01:9600"]
  username: "elastic"
  password: "changeme"
  xpack.enabled: true

- module: kibana
  enabled: true
  metricsets: ["status"]
  period: 10s
  hosts: ["http://kb01:5601"]
  username: "elastic"
  password: "changeme"
  xpack.enabled: true

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  xpack.enabled: true

# ================================== Outputs ===================================
output.elasticsearch:
  enabled: true
  hosts: ["es01:9200"]
  username: "elastic"
  password: "changeme"

# ================================== Template ==================================
setup.template.enabled: true
setup.template.overwrite: true
setup.template.pattern: "metricbeat-*"
setup.template.settings:
  index.number_of_replicas: 0
  index.number_of_shards: 1

# ================================= Dashboards =================================
# setup.dashboards.enabled: true
# setup.dashboards.directory: ${path.home}/kibana

# =================================== Kibana ===================================
setup.kibana:
  host: "http://kb01:5601"
  username: elastic
  password: "changeme"

# =============================== HTTP Endpoint ================================
# monitoring.enabled: false
# http.enabled: true
# http.port: 5068