############################# Auditbeat ######################################
auditbeat.modules:
- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

# ================================== Outputs ===================================
output.elasticsearch:
  enabled: true
  hosts: ["es01:9200"]
  username: "elastic"
  password: "changeme"

# ================================= Dashboards =================================
# setup.dashboards.enabled: true
# setup.dashboards.directory: ${path.home}/kibana

# =================================== Kibana ===================================
setup.kibana:
  host: "http://kb01:5601"
  username: elastic
  password: "changeme"

# ================================== Template ==================================
setup.template.enabled: true
setup.template.overwrite: true
setup.template.pattern: "auditbeat-*"
setup.template.settings:
  index.number_of_replicas: 0
  index.number_of_shards: 1

# =============================== HTTP Endpoint ================================
monitoring.enabled: false
http.enabled: true
http.port: 5069
